Fix replacement of conditional user-defined macros
Users can define custom macros by setting
`spec.macros['my_macro'] = 'my_value'`. This worked fine up to the 0.14
release, where commit 37e129bef531630de0ac7c8e952d2b40b817f22c broke
this behavior in what seems like an unintended side effect from a
refactoring:

```
  File "pyrpm/spec.py", line 548, in replace_macros
    ret = re.sub(_macro_pattern, _macro_repl, string)
  File "/usr/lib64/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "pyrpm/spec.py", line 526, in _macro_repl
    return spec.macros.get(parts[0], getattr(spec, parts[0]))
AttributeError: 'Spec' object has no attribute 'dist'
```

Bring the old behavior back, and add a test for it.